import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className="bg-white container mx-auto bg-gradient-to-b from-[#CECA30] via-[#2554A4] to-[#32A1DA]"> */}
      <body className="bg-white container mx-auto bg-gradient-to-b from-blue-100 via-blue-50 to-blue-100">

        <div className=" ">
        <Navbar />
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  );
}
